server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mahmoud11Ashour/trainconnect-config
          clone-on-start: true
          default-label: main
